### PR TITLE
#61 - Allow AWSVPC support

### PR DESCRIPTION
**Pull request by sopeters**
Should solve #61

### CODE REVIEW

**Comment by fabfuel** [comment]
Hi @sopeters & thanks for your PR!

The problem is, that in your implementation it's now required to have a configured service to run a (previously) independent task and this is not always the case. It's not required to set up a service at all, all you need to run a one-off task is the task definition itself. That means, the network configuration needs to be passed explicitly to the `run` command and it may to be fetched from a service - maybe optionally, but this may not be required.

Best
Fabian

**Comment by sopeters** [comment]
Good point. Forgot about that as I’m using it for one-off commands on existing services (DB migration scripts). Maybe you could have 2 run commands or as you said optional parameters. 

I’ll just keep this as a patch for my setup otherwise - maybe other people can use it too. 

Difficult to solve for a non existent service - you’ll need to provide VPC, Subnets, SGs

**Comment by fabfuel** [comment]
> Difficult to solve for a non existent service - you’ll need to provide VPC, Subnets, SGs

Yes, exactly, that's the only way to do it. I started a branch for this additional parameters. If you have a fargate based setup and if you could test this version of ecs-deploy, that would be highly appreciated! Any feedback is welcome 🙂 

https://github.com/fabfuel/ecs-deploy/tree/run-task-fargate

The new, required parameters for fargate are:
- `launchtype`
- `subnet`
- `securitygroup`
- `public-ip`

Best 
Fabian

**Comment by sopeters** [comment]
Hi Fabian

I’m all on EC2 - sorry. 

Happy to test on EC2. Would be good if your branch could also have an option for reading from existing services - I don’t want to supply the params as I keep infrastructure in Cloudformation

**Comment by fabfuel** [comment]
I'll close this PR for now. This should be a new feature "run task from service definition" which needs some refactoring. Best, Fabian

**Pull request closed without merging**
