### PR TITLE
Add environmentfiles parameter

### PR DESCRIPTION
**Pull request by mjmayer**
Add support for the ECS task definition parameter `environmentFiles` 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html

### CODE REVIEW

**Comment by mjmayer** [comment]
@fabfuel Are the CI checks having problems? It seems like Scrutinizer and travis-ci are in some kind of broken state.

**Comment by fabfuel** [comment]
Hi Michael,

the free Travis CI recently shut down its service and I still need to migrate the project to travis-ci.com. Scrutinizer is depending on the coverage report from Travis, therefore this is currently failing, too.

Best
Fabian

**Comment by fabfuel** [comment]
Hi Michael, the tests are running again, but there is one test failing in Python 2.7:
https://travis-ci.com/github/fabfuel/ecs-deploy/builds/234348638

Best
Fabian

**Comment by mjmayer** [comment]
Hmmm... The test `test_task_set_s3_env_file_exclusively` is only failing when run from tox. I've never used tox before, but I'll poke around a bit to see if I can find out why it is failing.

**Comment by mjmayer** [comment]
After some gnarly conflicts when I rebased I got tests passing.

I figured out the issue with Python 2.7. Apparently `unicode` is not the same thing as `str`. I believe I ended up with a better solution when trying to work around the type difference.

**Comment by fabfuel** [comment]
Thanks a lot Michael, your effort is highly appreciated! :-)

**Pull request merged**
